name: "changelog-syncer"
description: "Send a pull request description to a Notion Database."
author: "Mergify"
inputs:
  NOTION_API_TIMEOUT:
    required: false
    description: "Notion API timeout"
    default: "10"
  NOTION_API_KEY:
    required: true
    description: "Notion API key"
  NOTION_DATABASE_ID:
    required: true
    description: "Notion Database ID"
  NOTION_API_VERSION:
    required: false
    description: "Notion API version"
    default: "2022-06-28"
  PR_TITLE:
    description: "Pull request title"
    default: ${{ github.event.pull_request.title }}
  PR_DESCRIPTION:
    description: "Pull request description"
    default: ${{ github.event.pull_request.body }}
  PR_MERGED_AT:
    description: "Pull request merge date (e.g. 2011-01-26T19:01:12Z)"
    default: ${{ github.event.pull_request.merged_at }}
runs:
  using: "composite"
  steps:
    # - uses: actions/checkout@v3
    #   with:
    #     repository: " Mergifyio/gha-changelog-syncer"
    - name: Install poetry
      shell: bash
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: poetry
    - run: poetry install --only main --no-interaction
      shell: bash
    - run: poetry run gha_handler
      shell: bash
      env:
        NOTION_API_TIMEOUT: ${{ inputs.NOTION_API_TIMEOUT }}
        NOTION_API_KEY: ${{ inputs.NOTION_API_KEY }}
        NOTION_DATABASE_ID: ${{ inputs.NOTION_DATABASE_ID }}
        PR_TITLE: ${{ inputs.PR_TITLE }}
        PR_DESCRIPTION: ${{ inputs.PR_DESCRIPTION }}
        PR_MERGED_AT: ${{ inputs.PR_MERGED_AT }}
